#!/bin/sh

set -e
if [ "$#" -ne 1 ]; then
    echo "1 argument required, $# provided"
    exit 1
fi

if [ -d "$1" ]; then
    echo "There's already a directory called '$1'."
    exit 1
fi

if  bb list | grep "$1"
then
    echo "There's already a repo called '$1'."
    exit 1
fi

if heroku apps | grep "^$1\$"
then
    echo "You already have a heroku app called '$1'."
    exit 1
fi

# exit if app name is taken
if heroku apps:info --app=$1 2>&1 >/dev/null | grep 'You do not have access'
then
    echo "Somebody else already claimed the heroku app name '$1'."
    exit 1
fi

if  bb list | grep "$1-api"
then
    echo "There's already a repo called '$1-api'."
    exit 1
fi

if heroku apps | grep "^$1-api\$"
then
    echo "You already have a heroku app called '$1-api'."
    exit 1
fi

if heroku apps:info --app=$1-api 2>&1 >/dev/null | grep 'You do not have access'
then
    echo "Somebody else already claimed the heroku app name '$1-api'."
    exit 1
fi

# Make base directory
mkdir $1
cd $1
subl .

# Make frontend app
mkdir frontend
cd frontend
ember init --name=$1

# Save to bitbucket
git init
git add .
git commit -m "Initial commit."
bb create $1 --private
git remote add origin git@bitbucket.org:gregsabo/$1.git
git push -u origin --all
git push -u origin --tags

cd ..

# Make API app
# cookiecutter --no-input https://github.com/JackStouffer/cookiecutter-Flask-Foundation
cookiecutter --no-input https://github.com/sloria/cookiecutter-flask
cd api
virtualenv env
. env/bin/activate

# Save to bitbucket
git init
git add .
git commit -m "Initial commit."
bb create $1-api --private
git remote add origin git@bitbucket.org:gregsabo/$1-api.git
git push -u origin --all
git push -u origin --tags

# initial deploys (do this last)

cd ..
cd frontend

# Deploy to heroku
heroku create --buildpack https://github.com/tonycoco/heroku-buildpack-ember-cli.git
git push heroku master
heroku apps:rename $1
heroku config:set API_URL=http://$1-api.herokuapp.com/api/
heroku config:set API_PREFIX_PATH=/api/

cd ..
cd api

# Deploy to heroku
heroku create
git push heroku master
heroku apps:rename $1-api

cd ..
