#!/bin/sh

set -e
if [ "$#" -ne 1 ]; then
    echo "1 argument required, $# provided"
    exit 1
fi

if [ -d "$1" ]; then
    echo "There's already a directory called '$1'."
    exit 1
fi

if  bb list | grep "$1"
then
    echo "There's already a repo called '$1'."
    exit 1
fi

if heroku apps | grep "^$1\$"
then
    echo "There's already a heroku app called '$1'."
    exit 1
fi

if  bb list | grep "$1-api"
then
    echo "There's already a repo called '$1-api'."
    exit 1
fi

if heroku apps | grep "^$1-api\$"
then
    echo "There's already a heroku app called '$1-api'."
    exit 1
fi

# Make base directory
mkdir $1
cd $1
subl .

# Make frontend app
mkdir frontend
cd frontend
ember init --name=$1

# Save to bitbucket
git init
git add .
git commit -m "Initial commit."
bb create $1 --private
git remote add origin git@bitbucket.org:gregsabo/$1.git
git push -u origin --all
git push -u origin --tags
cd ..

# Make API app
cookiecutter --no-input https://github.com/JackStouffer/cookiecutter-Flask-Foundation
cd api
make env
. env/bin/activate

# Save to bitbucket
git init
curl https://raw.githubusercontent.com/github/gitignore/master/Python.gitignore > .gitignore
git add .
git commit -m "Initial commit."
bb create $1-api --private
git remote add origin git@bitbucket.org:gregsabo/$1-api.git
git push -u origin --all
git push -u origin --tags
cd ..

# Make repos
# cd frontend
# bb create_from_local --private
# git push origin master

# heroku create --buildpack https://github.com/tonycoco/heroku-buildpack-ember-cli.git
# git push heroku master

# heroku apps:rename $1
